#%RAML 1.0
title: RetrieveConsolidatedRoutesAndSchedule TravelOnTip SAPI
description: This API will fectch Routes and Schedules from TravelOnTip System
  
uses:
  common: /libraries/common/common-business-library.raml
  routes: libraries/routes/routesBusiness-library.raml
  schedules: libraries/schedules/schedulesBusiness-library.raml


/{transportType}:
  /{transportCompany}:
    /routes:
      get:
        is:
          - common.transactionId
        responses:
          200:
            body:
              application/json:
                type: routes.getRoutesResponse
                example: !include /libraries/routes/examples/getRoutes-200Response-example.json      
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json      
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json      
    /schedules:
      get:
        is:
          - common.transactionId
          - common.departureLocationCode
          - common.destinationLocationCode
        responses:
          200:
            body:
              application/json:
                type: schedules.getSchedulesResponse
                example: !include /libraries/schedules/examples/getSchedules-200Response-example.json
                                    
          400:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/400Response-example.json
                  
          404:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/404Response-example.json
          500:
            body:
              application/json:
                type: common.commonError
                example: !include /libraries/common/examples/500Response-example.json
          
                      
